<?xml version="1.0"?>
<!DOCTYPE connection [
        <!ELEMENT root-element (host,port,credentials)>
        <!ELEMENT host (#PCDATA)>
        <!ELEMENT port (#PCDATA)>
        <!ELEMENT credentials (credential+)>
        <!ELEMENT credential (user, password)>
        <!ELEMENT user (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        ]>
<connection>
    <host>localhost</host>
    <port>3306</port>
    <credentials>
        <credential>
            <user>root</user>
            <password>root-secret</password>
        </credential>
        <credential>
            <user>user</user>
            <password>secret</password>
        </credential>
    </credentials>
</connection>
